GET http://localhost:3003/api/blogs
###
POST http://localhost:3003/api/blogs/ 
content-type: application/json

{
    "title": "sample blog 2",
    "author": "o.s.",
    "url": "www.sample.org",
    "likes": 7
}
